#!/bin/bash

. common.test

if [ "$TEST_CMDMON_VARIANT" = "1" ]; then
	export CLKNETSIM_FUZZ_MODE=1 CLKNETSIM_FUZZ_SUBNET=1 CLKNETSIM_FUZZ_PORT=323
	cmdaddress=0.0.0.0
elif [ "$TEST_CMDMON_VARIANT" = "2" ]; then
	export CLKNETSIM_FUZZ_MODE=1 CLKNETSIM_FUZZ_SUBNET=1 CLKNETSIM_FUZZ_PORT=323 CLKNETSIM_IP_FAMILY=6
	cmdaddress=::
else
	export CLKNETSIM_FUZZ_MODE=1 CLKNETSIM_FUZZ_SUBNET=2 CLKNETSIM_FUZZ_PORT=1
	cmdaddress=127.0.0.1
fi
export TEST_PREFILL_CLIENTLOG=16

seed_command=(chronyc -h '/clknetsim/unix/1:1' -n -m)
while read c; do
	seed_command+=("$c")
done < <(grep -Pzo '\n *chronyc_conf="[^"]*"\n' "$WORK_DIR/chrony/test/simulation/110-chronyc" | \
	sed 's/\(^[^"]*="\|"[^"]*$\)//g' | sort -u | grep -aviE '(nosuch|waitsync)')

run_test chronyd -d -d \
	'bindcmdaddress /clknetsim/unix/chronyd.sock' \
	"bindcmdaddress $cmdaddress" \
	'cmdallow' \
	'opencommands activity authdata clients manual ntpdata rtcdata selectdata serverstats smoothing sourcename sources sourcestats tracking' \
	'dumpdir dumpdir' \
	'keyfile data/chrony.keys' \
	'local stratum 5' \
	'manual' \
	'server 192.168.123.4' \
	'server 192.168.123.6 nts offline' \
	'server node2.net1.clk key 2' \
	'server noexist.net1.clk' \
	'refclock PHC /dev/ptp0' \
	'smoothtime 400 0.001'
