#!/bin/bash

. common.test

export CLKNETSIM_FUZZ_MODE=1 CLKNETSIM_FUZZ_SUBNET=2 CLKNETSIM_FUZZ_PORT=1

seed_command=(chronyc -h '/clknetsim/unix/1:1' -n -m)
while read c; do
	seed_command+=("$c")
done < <(grep -Pzo '\n *chronyc_conf="[^"]*"\n' "$WORK_DIR/chrony/test/simulation/110-chronyc" | \
	sed 's/\(^[^"]*="\|"[^"]*$\)//g' | sort -u | grep -aviE '(nosuch|waitsync)')

run_test chronyd -d -d \
	'bindcmdaddress /clknetsim/unix/chronyd.sock' \
	'dumpdir dumpdir' \
	'keyfile data/chrony.keys' \
	'local stratum 5' \
	'manual' \
	'server 192.168.123.4' \
	'server 192.168.123.6 nts offline' \
	'server node2.net1.clk key 2' \
	'server noexist.net1.clk' \
	'smoothtime 400 0.001'
