#!/bin/bash

. common.test

export CLKNETSIM_FUZZ_MODE=3 CLKNETSIM_FUZZ_PORT=4460 CLKNETSIM_FUZZ_START=0.3
export CLKNETSIM_FUZZ_MSG_TYPE=3

run_test chronyd -d -d -t 100 \
	'acquisitionport 4460' \
	'makestep 10 2' \
	'server node2.net1.clk iburst nts'
