#!/bin/bash

. common.test

export CLKNETSIM_FUZZ_MODE=3 CLKNETSIM_FUZZ_PORT=123

seed_command=(chronyd -d \
	'allow' \
	'local' \
	'ntsprocesses 0' \
	'ntsserverkey data/emptydir/server.key' \
	'ntsservercert data/emptydir/server.crt' )

run_test chronyd -d -d -t 5 \
	'acquisitionport 123' \
	'keyfile data/chrony.keys' \
	'makestep 10 2' \
	'ntsdumpdir data/ntsdumpdir' \
	'server node2.net1.clk iburst nts'
