#!/bin/bash

. common.test

export CLKNETSIM_FUZZ_MODE=4 CLKNETSIM_FUZZ_PORT=1
export TEST_STDIN_FILE="data/emptydir/192.168.123.1.nts"

run_test chronyd -d -d -t 2 \
	'server node1.net1.clk nts' \
	'ntsdumpdir data/emptydir'
