#!/bin/bash

. common.test

export CLKNETSIM_FUZZ_MODE=1 CLKNETSIM_FUZZ_PORT=319 CLKNETSIM_FUZZ_START=5.1
export CLKNETSIM_TIMESTAMPING=2

seed_command=(chronyd -d -t 5 \
	'ptpport 319' \
	'server node1.net1.clk port 319 extfield F323 extfield F324')

run_test chronyd -d -d \
	'allow' \
	'keyfile data/chrony.keys' \
	'hwtimestamp eth0' \
	'local stratum 5 orphan' \
	'ntpsigndsocket /clknetsim/unix/signd.socket' \
	'ptpport 319' \
	'server 192.168.123.4' \
	'server 192.168.123.5'
