#!/bin/bash

set -e

valgrind="valgrind --error-exitcode=129"
leak_opts="--leak-check=full --errors-for-leak-kinds=definite"

leak_exclude_regex="(config)"

for build_opts in "gcc nofuzz"; do
	for extra_conf_opts in \
		"" \
		"--disable-nts" \
		"--disable-ntp" \
		"--disable-ipv6"
	do
		scripts/build $build_opts $extra_conf_opts

		leak_tests=""
		other_tests=""
		for t in tests/*; do
			[ -d "$t" ] && continue
			[ -x "$t" ] || continue
			[[ "$(basename "$t")" =~ $leak_exclude_regex ]] && \
				other_tests+=" $t" || leak_tests+=" $t"
		done

		TEST_WRAPPER="$valgrind $leak_opts" scripts/check $leak_tests
		TEST_WRAPPER="$valgrind" scripts/check $other_tests
	done
done
