#!/bin/bash

set -e

[ -f env ] && . ./env

[ $# -ge 1 ] && dry_run=1 || dry_run=0

WORK_DIR=${WORK_DIR:-work}

export AFL_ALLOW_TMP=1

for i in input/*; do
	sums1=$(find "$i" -maxdepth 1 -type f -print0 | xargs -0 md5sum | sort)
	num1=$(echo "$sums1" | wc -l)
	echo -n "$(basename "$i"): $num1 -> "

	if ! TEST_MODE=minimize "tests/$(basename "$i")" &> "$WORK_DIR/cmin.log"; then
		echo
		tail "$WORK_DIR/cmin.log"
		exit 1
	fi

	queue=$WORK_DIR/output/$(basename "$i")/minimized
	sums2=$(find "$queue" -maxdepth 1 -type f -print0 | xargs -0 md5sum | sort)
	num2=$(echo "$sums2" | wc -l)

	echo "$num2"

	if [ "$num2" -lt 10 ]; then
		echo "Too few files"
		exit 1
	fi

	comm -1 -3 <(echo "$sums2" | cut -d ' ' -f 1) <(echo "$sums1" | cut -d ' ' -f 1) | \
		join -j 1 - <(echo "$sums1") | \
		while read -r _ in; do
			if [ "$dry_run" = "0" ]; then
				rm "$in"
			fi
		done
done
