#!/usr/bin/python3

import pcapy
import struct
import sys

if len(sys.argv) < 3:
    print("Usage: {} [-s] pcap...".format(sys.argv[0]), file=sys.stderr)
    sys.exit(1)

args = sys.argv[1:]
single = False

if args[0] == "-s":
    single = True
    args = args[1:]

for f in args:
    cap = pcapy.open_offline(f)

    while True:
        (header, frame) = cap.next()
        if len(frame) == 0:
            break

        if cap.datalink() == pcapy.DLT_EN10MB:
            udp_payload = bytearray(frame[14 + 20 + 8:])
        else:
            print("Unsupported datalink type")
            sys.exit(2)

        print(len(udp_payload), file=sys.stderr)

        if single:
            sys.stdout.buffer.write(udp_payload)
            sys.exit(0)
        else:
            hdr = struct.pack("!H", len(udp_payload))
            sys.stdout.buffer.write(hdr + udp_payload)
